/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * game.java
 *
 * Created on Oct 27, 2015, 8:24:12 PM
 */

/**
 *
 * @author Nibas Nazeemyy
 */
import javax.swing.*;
public class game extends javax.swing.JFrame {
      private Object score=5000;
       private Object pscore=0;
       public String fn;

    /** Creates new form game */
    public game() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlg = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        arb = new javax.swing.JRadioButton();
        brb = new javax.swing.JRadioButton();
        crb = new javax.swing.JRadioButton();
        drb = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        dlg2 = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        arb1 = new javax.swing.JRadioButton();
        crb1 = new javax.swing.JRadioButton();
        drb1 = new javax.swing.JRadioButton();
        brb1 = new javax.swing.JRadioButton();
        ok1 = new javax.swing.JButton();
        dlg3 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        arb2 = new javax.swing.JRadioButton();
        crb2 = new javax.swing.JRadioButton();
        drb2 = new javax.swing.JRadioButton();
        brb2 = new javax.swing.JRadioButton();
        ok2 = new javax.swing.JButton();
        dlg4 = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        arb3 = new javax.swing.JRadioButton();
        crb3 = new javax.swing.JRadioButton();
        drb3 = new javax.swing.JRadioButton();
        brb3 = new javax.swing.JRadioButton();
        ok3 = new javax.swing.JButton();
        dlg5 = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        arb4 = new javax.swing.JRadioButton();
        crb4 = new javax.swing.JRadioButton();
        drb4 = new javax.swing.JRadioButton();
        brb4 = new javax.swing.JRadioButton();
        ok4 = new javax.swing.JButton();
        dlg6 = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        crb5 = new javax.swing.JRadioButton();
        arb5 = new javax.swing.JRadioButton();
        drb5 = new javax.swing.JRadioButton();
        brb5 = new javax.swing.JRadioButton();
        ok5 = new javax.swing.JButton();
        dlg7 = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        arb9 = new javax.swing.JRadioButton();
        crb9 = new javax.swing.JRadioButton();
        drb9 = new javax.swing.JRadioButton();
        brb9 = new javax.swing.JRadioButton();
        ok9 = new javax.swing.JButton();
        dlg8 = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        arb6 = new javax.swing.JRadioButton();
        crb6 = new javax.swing.JRadioButton();
        drb6 = new javax.swing.JRadioButton();
        brb6 = new javax.swing.JRadioButton();
        ok6 = new javax.swing.JButton();
        dlg9 = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        arb7 = new javax.swing.JRadioButton();
        crb7 = new javax.swing.JRadioButton();
        drb7 = new javax.swing.JRadioButton();
        brb7 = new javax.swing.JRadioButton();
        ok7 = new javax.swing.JButton();
        dlg10 = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        arb8 = new javax.swing.JRadioButton();
        crb8 = new javax.swing.JRadioButton();
        drb8 = new javax.swing.JRadioButton();
        brb8 = new javax.swing.JRadioButton();
        ok8 = new javax.swing.JButton();
        dlg11 = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        arb10 = new javax.swing.JRadioButton();
        crb10 = new javax.swing.JRadioButton();
        drb10 = new javax.swing.JRadioButton();
        brb10 = new javax.swing.JRadioButton();
        ok10 = new javax.swing.JButton();
        dlg12 = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        arb11 = new javax.swing.JRadioButton();
        crb11 = new javax.swing.JRadioButton();
        drb11 = new javax.swing.JRadioButton();
        brb11 = new javax.swing.JRadioButton();
        ok11 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        EXIT = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lbtg = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ntf = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        dlg.setMinimumSize(new java.awt.Dimension(980, 385));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel2.setText("WHICH CITY IS THE MOST POPULATED CITY IN INDIA ?");

        ok.setFont(new java.awt.Font("Tahoma", 1, 48));
        ok.setText("CHECK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        buttonGroup1.add(arb);
        arb.setFont(new java.awt.Font("Tahoma", 1, 24));
        arb.setText("MUMBAI");

        buttonGroup1.add(brb);
        brb.setFont(new java.awt.Font("Tahoma", 1, 24));
        brb.setText("NEW DELHI");

        buttonGroup1.add(crb);
        crb.setFont(new java.awt.Font("Tahoma", 1, 24));
        crb.setText("KOLKATA");

        buttonGroup1.add(drb);
        drb.setFont(new java.awt.Font("Tahoma", 1, 24));
        drb.setText("CHENNAI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crb)
                    .addComponent(arb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 458, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(drb)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(brb)
                        .addGap(138, 138, 138))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(arb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crb)
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(brb)
                .addGap(18, 18, 18)
                .addComponent(drb, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel1.setOpaque(true);

        javax.swing.GroupLayout dlgLayout = new javax.swing.GroupLayout(dlg.getContentPane());
        dlg.getContentPane().setLayout(dlgLayout);
        dlgLayout.setHorizontalGroup(
            dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgLayout.createSequentialGroup()
                .addGroup(dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(dlgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dlgLayout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(ok))
                    .addGroup(dlgLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        dlgLayout.setVerticalGroup(
            dlgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlgLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ok)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        dlg2.setFont(new java.awt.Font("Agency FB", 1, 48));
        dlg2.setMinimumSize(new java.awt.Dimension(799, 335));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel3.setText("Which of these is a character from the 'Thousand and One Nights'?");
        jLabel3.setPreferredSize(new java.awt.Dimension(798, 320));

        buttonGroup1.add(arb1);
        arb1.setFont(new java.awt.Font("Tahoma", 1, 24));
        arb1.setText("Aladdin");

        buttonGroup1.add(crb1);
        crb1.setFont(new java.awt.Font("Tahoma", 1, 24));
        crb1.setText("Baba Yaga");

        buttonGroup1.add(drb1);
        drb1.setFont(new java.awt.Font("Tahoma", 1, 24));
        drb1.setText("Tintin");

        buttonGroup1.add(brb1);
        brb1.setFont(new java.awt.Font("Tahoma", 1, 24));
        brb1.setText("Othello");

        ok1.setFont(new java.awt.Font("Tahoma", 1, 24));
        ok1.setText("Check");
        ok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlg2Layout = new javax.swing.GroupLayout(dlg2.getContentPane());
        dlg2.getContentPane().setLayout(dlg2Layout);
        dlg2Layout.setHorizontalGroup(
            dlg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg2Layout.createSequentialGroup()
                .addGroup(dlg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlg2Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(ok1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dlg2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(dlg2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arb1)
                    .addComponent(crb1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 386, Short.MAX_VALUE)
                .addGroup(dlg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brb1)
                    .addComponent(drb1))
                .addGap(258, 258, 258))
        );
        dlg2Layout.setVerticalGroup(
            dlg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlg2Layout.createSequentialGroup()
                        .addComponent(arb1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(crb1)
                        .addGap(46, 46, 46)
                        .addComponent(ok1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dlg2Layout.createSequentialGroup()
                        .addComponent(brb1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(drb1)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        dlg3.setFont(new java.awt.Font("Agency FB", 1, 48));
        dlg3.setMinimumSize(new java.awt.Dimension(890, 349));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel4.setText("What name is given to the part of an aeroplane where a pilot sits");

        buttonGroup1.add(arb2);
        arb2.setFont(new java.awt.Font("Tahoma", 1, 24));
        arb2.setText("Pulpit");

        buttonGroup1.add(crb2);
        crb2.setFont(new java.awt.Font("Tahoma", 1, 24));
        crb2.setText("cockpit");

        buttonGroup1.add(drb2);
        drb2.setFont(new java.awt.Font("Tahoma", 1, 24));
        drb2.setText("Pitstop");

        buttonGroup1.add(brb2);
        brb2.setFont(new java.awt.Font("Tahoma", 1, 24));
        brb2.setText("Soakpit");

        ok2.setFont(new java.awt.Font("Tahoma", 1, 24));
        ok2.setText("Check");
        ok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlg3Layout = new javax.swing.GroupLayout(dlg3.getContentPane());
        dlg3.getContentPane().setLayout(dlg3Layout);
        dlg3Layout.setHorizontalGroup(
            dlg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlg3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlg3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(dlg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arb2)
                            .addComponent(drb2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 488, Short.MAX_VALUE)
                        .addGroup(dlg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(crb2)
                            .addComponent(brb2))
                        .addGap(156, 156, 156))))
            .addGroup(dlg3Layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addComponent(ok2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(437, Short.MAX_VALUE))
        );
        dlg3Layout.setVerticalGroup(
            dlg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg3Layout.createSequentialGroup()
                .addGroup(dlg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlg3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brb2))
                    .addGroup(dlg3Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(arb2)))
                .addGroup(dlg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlg3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(crb2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ok2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dlg3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(drb2)))
                .addGap(97, 97, 97))
        );

        dlg4.setFont(new java.awt.Font("Agency FB", 1, 48));
        dlg4.setMinimumSize(new java.awt.Dimension(937, 337));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel5.setText("Durring which of these situations might a caesarian operation be performed");

        buttonGroup1.add(arb3);
        arb3.setFont(new java.awt.Font("Tahoma", 1, 24));
        arb3.setText("Heart Attack");

        buttonGroup1.add(crb3);
        crb3.setFont(new java.awt.Font("Tahoma", 1, 24));
        crb3.setText("Haemorrhage");

        buttonGroup1.add(drb3);
        drb3.setFont(new java.awt.Font("Tahoma", 1, 24));
        drb3.setText("Child Birth");

        buttonGroup1.add(brb3);
        brb3.setFont(new java.awt.Font("Tahoma", 1, 24));
        brb3.setText("Brain Tumour");

        ok3.setFont(new java.awt.Font("Tahoma", 1, 24));
        ok3.setText("check");
        ok3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlg4Layout = new javax.swing.GroupLayout(dlg4.getContentPane());
        dlg4.getContentPane().setLayout(dlg4Layout);
        dlg4Layout.setHorizontalGroup(
            dlg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlg4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(dlg4Layout.createSequentialGroup()
                        .addGroup(dlg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arb3)
                            .addComponent(crb3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 456, Short.MAX_VALUE)
                        .addGroup(dlg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drb3)
                            .addComponent(brb3))
                        .addGap(110, 110, 110))))
            .addGroup(dlg4Layout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(ok3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(428, Short.MAX_VALUE))
        );
        dlg4Layout.setVerticalGroup(
            dlg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dlg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlg4Layout.createSequentialGroup()
                        .addComponent(brb3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(drb3)
                        .addContainerGap())
                    .addGroup(dlg4Layout.createSequentialGroup()
                        .addComponent(arb3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(crb3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(ok3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        dlg5.setMinimumSize(new java.awt.Dimension(854, 348));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel6.setText(" In Indian taxation terminology, what does the 'P' in PAN stand for?");

        arb4.setFont(new java.awt.Font("Tahoma", 1, 24));
        arb4.setText(" Permenent");

        crb4.setFont(new java.awt.Font("Tahoma", 1, 24));
        crb4.setText("Personal");

        drb4.setFont(new java.awt.Font("Tahoma", 1, 24));
        drb4.setText(" Public");

        brb4.setFont(new java.awt.Font("Tahoma", 1, 24));
        brb4.setText(" Private");

        ok4.setFont(new java.awt.Font("Tahoma", 1, 24));
        ok4.setText("Check");
        ok4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlg5Layout = new javax.swing.GroupLayout(dlg5.getContentPane());
        dlg5.getContentPane().setLayout(dlg5Layout);
        dlg5Layout.setHorizontalGroup(
            dlg5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg5Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 834, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(dlg5Layout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(ok4)
                .addContainerGap(397, Short.MAX_VALUE))
            .addGroup(dlg5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(dlg5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brb4)
                    .addComponent(crb4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 440, Short.MAX_VALUE)
                .addGroup(dlg5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drb4)
                    .addComponent(arb4))
                .addGap(89, 89, 89))
        );
        dlg5Layout.setVerticalGroup(
            dlg5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(dlg5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlg5Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(arb4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(drb4)
                        .addGap(63, 63, 63)
                        .addComponent(ok4))
                    .addGroup(dlg5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(brb4)
                        .addGap(8, 8, 8)
                        .addComponent(crb4)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        dlg6.setMinimumSize(new java.awt.Dimension(833, 330));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel7.setText(" what is the nationality of the ancient philosopher Confucius ?");

        buttonGroup1.add(crb5);
        crb5.setFont(new java.awt.Font("Tahoma", 1, 24));
        crb5.setText(" Chineese");

        buttonGroup1.add(arb5);
        arb5.setFont(new java.awt.Font("Tahoma", 1, 24));
        arb5.setText(" Portuguese");

        buttonGroup1.add(drb5);
        drb5.setFont(new java.awt.Font("Tahoma", 1, 24));
        drb5.setText("Japaneese");

        buttonGroup1.add(brb5);
        brb5.setFont(new java.awt.Font("Tahoma", 1, 24));
        brb5.setText(" Italian");

        ok5.setFont(new java.awt.Font("Tahoma", 1, 24));
        ok5.setText(" Check");
        ok5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlg6Layout = new javax.swing.GroupLayout(dlg6.getContentPane());
        dlg6.getContentPane().setLayout(dlg6Layout);
        dlg6Layout.setHorizontalGroup(
            dlg6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlg6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlg6Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(ok5))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
                    .addGroup(dlg6Layout.createSequentialGroup()
                        .addGroup(dlg6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arb5)
                            .addComponent(crb5))
                        .addGap(411, 411, 411)
                        .addGroup(dlg6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brb5)
                            .addComponent(drb5))))
                .addContainerGap())
        );
        dlg6Layout.setVerticalGroup(
            dlg6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlg6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlg6Layout.createSequentialGroup()
                        .addComponent(brb5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(drb5))
                    .addGroup(dlg6Layout.createSequentialGroup()
                        .addComponent(arb5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(crb5)))
                .addGap(36, 36, 36)
                .addComponent(ok5)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        dlg7.setMinimumSize(new java.awt.Dimension(713, 330));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel11.setText("Which of these Novels was written by Mulk Raj Anand ?");

        buttonGroup1.add(arb9);
        arb9.setFont(new java.awt.Font("Tahoma", 1, 24));
        arb9.setText(" The Guide");

        buttonGroup1.add(crb9);
        crb9.setFont(new java.awt.Font("Tahoma", 1, 24));
        crb9.setText(" Coolie");

        buttonGroup1.add(drb9);
        drb9.setFont(new java.awt.Font("Tahoma", 1, 24));
        drb9.setText(" The Blue Umbrella");

        buttonGroup1.add(brb9);
        brb9.setFont(new java.awt.Font("Tahoma", 1, 24));
        brb9.setText(" MY Days");

        ok9.setFont(new java.awt.Font("Tahoma", 1, 24));
        ok9.setText("Check");
        ok9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlg7Layout = new javax.swing.GroupLayout(dlg7.getContentPane());
        dlg7.getContentPane().setLayout(dlg7Layout);
        dlg7Layout.setHorizontalGroup(
            dlg7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dlg7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlg7Layout.createSequentialGroup()
                        .addGroup(dlg7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arb9)
                            .addComponent(drb9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                        .addGroup(dlg7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crb9)
                            .addComponent(brb9))
                        .addGap(116, 116, 116)))
                .addGap(38, 38, 38))
            .addGroup(dlg7Layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(ok9)
                .addContainerGap(334, Short.MAX_VALUE))
        );
        dlg7Layout.setVerticalGroup(
            dlg7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlg7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arb9)
                    .addComponent(brb9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlg7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlg7Layout.createSequentialGroup()
                        .addComponent(drb9)
                        .addGap(13, 13, 13)
                        .addComponent(ok9))
                    .addComponent(crb9))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        dlg8.setMinimumSize(new java.awt.Dimension(1095, 298));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel8.setText(" Which popular Pilgrimage spot in South india is set amoung sapthagri hills?");

        buttonGroup1.add(arb6);
        arb6.setFont(new java.awt.Font("Tahoma", 1, 24));
        arb6.setText("Madurai");

        buttonGroup1.add(crb6);
        crb6.setFont(new java.awt.Font("Tahoma", 1, 24));
        crb6.setText("Triupati");

        buttonGroup1.add(drb6);
        drb6.setFont(new java.awt.Font("Tahoma", 1, 24));
        drb6.setText("Chidambaram");

        buttonGroup1.add(brb6);
        brb6.setFont(new java.awt.Font("Tahoma", 1, 24));
        brb6.setText("Uduipi");

        ok6.setFont(new java.awt.Font("Tahoma", 1, 24));
        ok6.setText("CHECK");
        ok6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlg8Layout = new javax.swing.GroupLayout(dlg8.getContentPane());
        dlg8.getContentPane().setLayout(dlg8Layout);
        dlg8Layout.setHorizontalGroup(
            dlg8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg8Layout.createSequentialGroup()
                .addGroup(dlg8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlg8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dlg8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 1075, Short.MAX_VALUE)
                            .addGroup(dlg8Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(dlg8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(arb6)
                                    .addComponent(crb6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 529, Short.MAX_VALUE)
                                .addGroup(dlg8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(brb6)
                                    .addComponent(drb6))
                                .addGap(224, 224, 224))))
                    .addGroup(dlg8Layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(ok6)))
                .addContainerGap())
        );
        dlg8Layout.setVerticalGroup(
            dlg8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlg8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlg8Layout.createSequentialGroup()
                        .addComponent(arb6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(crb6)
                        .addGap(24, 24, 24)
                        .addComponent(ok6))
                    .addGroup(dlg8Layout.createSequentialGroup()
                        .addComponent(brb6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(drb6)))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        dlg9.setMinimumSize(new java.awt.Dimension(1067, 336));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel9.setText("Which legendary singer and actor was origamnnly a typewritter salesman ?");

        buttonGroup1.add(arb7);
        arb7.setFont(new java.awt.Font("Tahoma", 1, 24));
        arb7.setText("K L Saigal");

        buttonGroup1.add(crb7);
        crb7.setFont(new java.awt.Font("Tahoma", 1, 24));
        crb7.setText("Kishore Kumar");

        buttonGroup1.add(drb7);
        drb7.setFont(new java.awt.Font("Tahoma", 1, 24));
        drb7.setText("Talat Mehmood");

        buttonGroup1.add(brb7);
        brb7.setFont(new java.awt.Font("Tahoma", 1, 24));
        brb7.setText("Mukesh");

        ok7.setFont(new java.awt.Font("Tahoma", 1, 24));
        ok7.setText("Check");
        ok7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlg9Layout = new javax.swing.GroupLayout(dlg9.getContentPane());
        dlg9.getContentPane().setLayout(dlg9Layout);
        dlg9Layout.setHorizontalGroup(
            dlg9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg9Layout.createSequentialGroup()
                .addGroup(dlg9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlg9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dlg9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE)
                            .addGroup(dlg9Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(dlg9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(arb7)
                                    .addComponent(crb7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 464, Short.MAX_VALUE)
                                .addGroup(dlg9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(drb7)
                                    .addComponent(brb7))
                                .addGap(161, 161, 161))))
                    .addGroup(dlg9Layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(ok7, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dlg9Layout.setVerticalGroup(
            dlg9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg9Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dlg9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlg9Layout.createSequentialGroup()
                        .addComponent(arb7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(crb7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ok7))
                    .addGroup(dlg9Layout.createSequentialGroup()
                        .addComponent(brb7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(drb7)))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        dlg10.setMinimumSize(new java.awt.Dimension(883, 266));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel10.setText("In which state was the Bhoodan Movement launched by vinoba Bhave?");

        buttonGroup1.add(arb8);
        arb8.setFont(new java.awt.Font("Tahoma", 1, 24));
        arb8.setText("Uttar Pradesh");

        buttonGroup1.add(crb8);
        crb8.setFont(new java.awt.Font("Tahoma", 1, 24));
        crb8.setText("Andhra Pradesh");

        buttonGroup1.add(drb8);
        drb8.setFont(new java.awt.Font("Tahoma", 1, 24));
        drb8.setText("Maharashatra");

        buttonGroup1.add(brb8);
        brb8.setFont(new java.awt.Font("Tahoma", 1, 24));
        brb8.setText("Madhya Pradesh");

        ok8.setFont(new java.awt.Font("Tahoma", 1, 24));
        ok8.setText("Check");
        ok8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlg10Layout = new javax.swing.GroupLayout(dlg10.getContentPane());
        dlg10.getContentPane().setLayout(dlg10Layout);
        dlg10Layout.setHorizontalGroup(
            dlg10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg10Layout.createSequentialGroup()
                .addGroup(dlg10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlg10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(dlg10Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(dlg10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arb8)
                            .addComponent(brb8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(ok8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addGroup(dlg10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drb8)
                            .addComponent(crb8))
                        .addGap(122, 122, 122)))
                .addGap(24, 24, 24))
        );
        dlg10Layout.setVerticalGroup(
            dlg10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(dlg10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlg10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dlg10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dlg10Layout.createSequentialGroup()
                                .addGroup(dlg10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(arb8)
                                    .addComponent(crb8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(brb8))
                            .addGroup(dlg10Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(drb8))))
                    .addGroup(dlg10Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(ok8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        dlg11.setMinimumSize(new java.awt.Dimension(713, 330));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel12.setText("Whichof these is the oldest indian Paramilitary force ?");

        buttonGroup1.add(arb10);
        arb10.setFont(new java.awt.Font("Tahoma", 1, 24));
        arb10.setText(" Assam Rifles");

        buttonGroup1.add(crb10);
        crb10.setFont(new java.awt.Font("Tahoma", 1, 24));
        crb10.setText(" Indo-Tibetan BP");

        buttonGroup1.add(drb10);
        drb10.setFont(new java.awt.Font("Tahoma", 1, 24));
        drb10.setText("NSG");

        buttonGroup1.add(brb10);
        brb10.setFont(new java.awt.Font("Tahoma", 1, 24));
        brb10.setText(" BSF");

        ok10.setFont(new java.awt.Font("Tahoma", 1, 24));
        ok10.setText(" Check");
        ok10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlg11Layout = new javax.swing.GroupLayout(dlg11.getContentPane());
        dlg11.getContentPane().setLayout(dlg11Layout);
        dlg11Layout.setHorizontalGroup(
            dlg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg11Layout.createSequentialGroup()
                .addGroup(dlg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlg11Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(dlg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlg11Layout.createSequentialGroup()
                                .addGroup(dlg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dlg11Layout.createSequentialGroup()
                                        .addComponent(crb10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                                        .addComponent(drb10))
                                    .addGroup(dlg11Layout.createSequentialGroup()
                                        .addComponent(arb10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(brb10)))
                                .addGap(124, 124, 124))))
                    .addGroup(dlg11Layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(ok10)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        dlg11Layout.setVerticalGroup(
            dlg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg11Layout.createSequentialGroup()
                .addGroup(dlg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlg11Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dlg11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(arb10)
                            .addComponent(brb10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(drb10))
                    .addGroup(dlg11Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(crb10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(ok10)
                .addGap(72, 72, 72))
        );

        dlg12.setMinimumSize(new java.awt.Dimension(871, 296));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel13.setText(" Who was the Independent India's first ambasodor to the USSR ?");

        buttonGroup1.add(arb11);
        arb11.setFont(new java.awt.Font("Tahoma", 1, 24));
        arb11.setText(" Sarojini Naidu");

        buttonGroup1.add(crb11);
        crb11.setFont(new java.awt.Font("Tahoma", 1, 24));
        crb11.setText(" Acharya Kripalani");

        buttonGroup1.add(drb11);
        drb11.setFont(new java.awt.Font("Tahoma", 1, 24));
        drb11.setText(" Vijayalakshmi Pandit");

        buttonGroup1.add(brb11);
        brb11.setFont(new java.awt.Font("Tahoma", 1, 24));
        brb11.setText(" S.Radhakrishnan");

        ok11.setFont(new java.awt.Font("Tahoma", 1, 24));
        ok11.setText(" Check");
        ok11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlg12Layout = new javax.swing.GroupLayout(dlg12.getContentPane());
        dlg12.getContentPane().setLayout(dlg12Layout);
        dlg12Layout.setHorizontalGroup(
            dlg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg12Layout.createSequentialGroup()
                .addGroup(dlg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dlg12Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(dlg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arb11)
                            .addComponent(crb11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                        .addGroup(dlg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drb11)
                            .addComponent(brb11))
                        .addGap(55, 55, 55)))
                .addGap(93, 93, 93))
            .addGroup(dlg12Layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(ok11)
                .addContainerGap(451, Short.MAX_VALUE))
        );
        dlg12Layout.setVerticalGroup(
            dlg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlg12Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arb11)
                    .addComponent(brb11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dlg12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crb11)
                    .addComponent(drb11))
                .addGap(27, 27, 27)
                .addComponent(ok11)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        EXIT.setBackground(new java.awt.Color(0, 0, 0));
        EXIT.setMinimumSize(new java.awt.Dimension(1030, 772));
        EXIT.getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 0, 98));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 48));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        EXIT.getContentPane().add(jButton1);
        jButton1.setBounds(450, 420, 170, 50);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("“Who Wants To Be A Millionaire” JAVA NetBeans IDE   "); // NOI18N
        EXIT.getContentPane().add(jLabel15);
        jLabel15.setBounds(170, 50, 680, 40);

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Designed and Created by C4 IT1");
        EXIT.getContentPane().add(jLabel20);
        jLabel20.setBounds(300, 630, 490, 50);

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Edition");
        EXIT.getContentPane().add(jLabel21);
        jLabel21.setBounds(820, 50, 100, 40);

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon("D:\\pro\\New Bitmap Image (2).png")); // NOI18N
        jLabel16.setText("jLabel16");
        jLabel16.setMaximumSize(new java.awt.Dimension(1122, 700));
        EXIT.getContentPane().add(jLabel16);
        jLabel16.setBounds(0, 0, 1020, 680);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 98));
        setMinimumSize(new java.awt.Dimension(633, 600));
        getContentPane().setLayout(null);

        lbtg.setBackground(new java.awt.Color(0, 0, 255));
        lbtg.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48));
        lbtg.setForeground(new java.awt.Color(255, 255, 255));
        lbtg.setText("LET'S BEGIN THE GAME");
        lbtg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbtgActionPerformed(evt);
            }
        });
        getContentPane().add(lbtg);
        lbtg.setBounds(10, 420, 600, 50);

        jLabel14.setIcon(new javax.swing.ImageIcon("D:\\pro\\Who Wants To Be A Millionaire Original UK Intro 2004 HD.gif")); // NOI18N
        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(150, 90, 320, 240);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("DISCLAMER:NO MONEY WILL BE GIVEN TO THE WINNERS,THIS IS JUST A SIMPLE PROGRAM");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 470, 620, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("ENTER YOUR NAME :");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(0, 500, 230, 50);

        ntf.setFont(new java.awt.Font("Tahoma", 1, 24));
        getContentPane().add(ntf);
        ntf.setBounds(240, 500, 350, 50);

        jLabel19.setBackground(new java.awt.Color(0, 0, 225));
        jLabel19.setOpaque(true);
        getContentPane().add(jLabel19);
        jLabel19.setBounds(0, 470, 620, 90);

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 1, 36));
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("WHO WANTS TO BE");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(120, 10, 390, 60);

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 1, 36));
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("WHO WANTS TO BE");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(120, 10, 390, 60);

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 1, 36));
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("MILLIONAIRE");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(180, 350, 280, 50);

        jLabel26.setText("jLabel26");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(160, 334, 290, 60);

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 1, 36));
        jLabel22.setText("jLabel22");
        jLabel22.setOpaque(true);
        getContentPane().add(jLabel22);
        jLabel22.setBounds(0, 0, 620, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbtgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbtgActionPerformed
JOptionPane.showMessageDialog(null,"WHO?, WHEN?, WHAT?, HOW? ,WHERE? QUESTIONS \n ARE A PART OF EVERY DAY LIFE. \n WHILE SOME QUESTION MAKE RACK OF OUR BRAIN , \n OTHERS CAN MAKE US NERVOUS AND BOGGLED .\n QUESTIONS ALSO CHANGE PEOPLES PERCEPTIONS, \n SOME HAVE POWER TO CHANGE LIVES AS WELL . \n BUT ONLY WHEN ANSWERED CORRECTLY ");
fn =(ntf.getText());
dlg.setVisible(true);
// TODO add your handling code here:
}//GEN-LAST:event_lbtgActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
if(crb.isSelected())
{
    JOptionPane.showMessageDialog(null,fn + ",Your answer is correct");
         score=10000;
    JOptionPane.showMessageDialog(null," Your have won RS"+score);
  
       dlg.setVisible(false);
       dlg2.setVisible(true);
}
else
{
 JOptionPane.showMessageDialog(null,"Sorry,Your answer is incorrect");
 JOptionPane.showMessageDialog(null,fn + ",Your have won"+0);
 JOptionPane.showMessageDialog(null,"\t\t GAME OVER");
 EXIT.setVisible(true);}// TODO add your handling code here:
}//GEN-LAST:event_okActionPerformed

    private void ok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok1ActionPerformed
if(arb1.isSelected())
{
    JOptionPane.showMessageDialog(null,fn + ",Your answer is correct");
     score=20000;
    JOptionPane.showMessageDialog(null," Your have won RS"+score);
      
       dlg2.setVisible(false);
       dlg3.setVisible(true);
}
else
{
 JOptionPane.showMessageDialog(null,"Sorry,Your answer is incorrect");
  JOptionPane.showMessageDialog(null,fn + ",Your have won"+score);
 JOptionPane.showMessageDialog(null,"\t\t GAME OVER");
 EXIT.setVisible(true);}// TODO add your handling code here:
    }//GEN-LAST:event_ok1ActionPerformed

    private void ok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok2ActionPerformed
if(crb2.isSelected())
{
    JOptionPane.showMessageDialog(null,fn + ",Your answer is correct");
     score=40000;
  JOptionPane.showMessageDialog(null," Your have won RS "+score);
      
       dlg3.setVisible(false);
       dlg4.setVisible(true);
}
else
{
 JOptionPane.showMessageDialog(null,"Sorry,Your answer is incorrect");
 JOptionPane.showMessageDialog(null,fn + ",Your have won"+0);
 JOptionPane.showMessageDialog(null,"\t\t GAME OVER");
 EXIT.setVisible(true);}// TODO add your handling code here:
    }//GEN-LAST:event_ok2ActionPerformed

    private void ok4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok4ActionPerformed
if(arb4.isSelected())
{
    JOptionPane.showMessageDialog(null,fn + ",Your answer is correct");
    score=80000;
   JOptionPane.showMessageDialog(null," Your have won RS "+score);
       
       dlg5.setVisible(false);
       dlg6.setVisible(true);
}
else
{
 JOptionPane.showMessageDialog(null,"Sorry,Your answer is incorrect");
 JOptionPane.showMessageDialog(null,fn + ",Your have won"+0);
 JOptionPane.showMessageDialog(null,"\t\t GAME OVER");
 EXIT.setVisible(true);}// TODO add your handling code here:
    }//GEN-LAST:event_ok4ActionPerformed

    private void ok5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok5ActionPerformed
if(crb5.isSelected())
{
    JOptionPane.showMessageDialog(null,fn + ",Your answer is correct");
    score=1600000;
   JOptionPane.showMessageDialog(null," Your have won RS "+score);
       
       dlg6.setVisible(false);
       dlg7.setVisible(true);
}
else
{
 JOptionPane.showMessageDialog(null,"Sorry,Your answer is incorrect");
 JOptionPane.showMessageDialog(null,fn + ",Your have won"+0);
 JOptionPane.showMessageDialog(null,"\t\t GAME OVER");
 EXIT.setVisible(true);}// TODO add your handling code here:
    }//GEN-LAST:event_ok5ActionPerformed

    private void ok6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok6ActionPerformed
if(crb6.isSelected())
{
    JOptionPane.showMessageDialog(null,fn + ",Your answer is correct");
    score=32000000;
   JOptionPane.showMessageDialog(null," Your have won RS "+score);

       dlg8.setVisible(false);
       dlg9.setVisible(true);
}
else
{
 JOptionPane.showMessageDialog(null,"Sorry,Your answer is incorrect");
  JOptionPane.showMessageDialog(null,fn + ",Your have won"+score);
 JOptionPane.showMessageDialog(null,"\t\t GAME OVER");
 EXIT.setVisible(true);}// TODO add your handling code here:
    }//GEN-LAST:event_ok6ActionPerformed

    private void ok7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok7ActionPerformed
if(arb7.isSelected())
{
    JOptionPane.showMessageDialog(null,fn + ",Your answer is correct");
    score=6400000;
   JOptionPane.showMessageDialog(null," Your have won RS "+score);
       
       dlg9.setVisible(false);
       dlg10.setVisible(true);
}
else
{
 JOptionPane.showMessageDialog(null,"Sorry,Your answer is incorrect");
 JOptionPane.showMessageDialog(null,fn + ",Your have won"+0);
 JOptionPane.showMessageDialog(null,"\t\t GAME OVER");
 EXIT.setVisible(true);}// TODO add your handling code here:
    }//GEN-LAST:event_ok7ActionPerformed

    private void ok8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok8ActionPerformed
if(crb8.isSelected())
{
    JOptionPane.showMessageDialog(null,fn + ",Your answer is correct");
    score=1250000;
   JOptionPane.showMessageDialog(null," Your have won RS "+score);

       
       dlg10.setVisible(false);
       dlg11.setVisible(true);
}
else
{
 JOptionPane.showMessageDialog(null,"Sorry,Your answer is incorrect");
 JOptionPane.showMessageDialog(null,fn + ",Your have won"+0);
 JOptionPane.showMessageDialog(null,"\t\t GAME OVER");
 EXIT.setVisible(true);}// TODO add your handling code here:
    }//GEN-LAST:event_ok8ActionPerformed

private void ok9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok9ActionPerformed
if(crb9.isSelected())
{
    JOptionPane.showMessageDialog(null,fn + ",Your answer is correct");
           score=2500000;
JOptionPane.showMessageDialog(null," Your have won RS "+score);

       dlg7.setVisible(false);
       dlg8.setVisible(true);
}
else
{
 JOptionPane.showMessageDialog(null,"Sorry,Your answer is incorrect");
 JOptionPane.showMessageDialog(null,fn + ",Your have won"+0);
 JOptionPane.showMessageDialog(null,"\t\t GAME OVER");
 EXIT.setVisible(true);}    // TODO add your handling code here:
}//GEN-LAST:event_ok9ActionPerformed

private void ok10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok10ActionPerformed
if(arb10.isSelected())
{
    JOptionPane.showMessageDialog(null,fn + ",Your answer is correct");
    score=5000000;
   JOptionPane.showMessageDialog(null," Your have won RS "+score);      
       dlg11.setVisible(false);
       dlg12.setVisible(true);
}
else
{
 JOptionPane.showMessageDialog(null,"Sorry,Your answer is incorrect");
  JOptionPane.showMessageDialog(null,fn + ",Your have won"+0);
 JOptionPane.showMessageDialog(null,"\t\t GAME OVER");
 EXIT.setVisible(true);}// TODO add your handling code here:
}//GEN-LAST:event_ok10ActionPerformed

private void ok11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok11ActionPerformed
if(drb11.isSelected())
{
    JOptionPane.showMessageDialog(null,fn + ",Your are a millionaire");
     score=100000000;
    JOptionPane.showMessageDialog(null," Your have won RS "+score);
      
       dlg12.setVisible(false);
       EXIT.setVisible(true);
}
else
{
 JOptionPane.showMessageDialog(null,"Sorry,Your answer is incorrect");
  JOptionPane.showMessageDialog(null,fn + ",Your have won"+score);
 JOptionPane.showMessageDialog(null,"\t\t GAME OVER");
 EXIT.setVisible(true);}// TODO add your handling code here:
}//GEN-LAST:event_ok11ActionPerformed

private void ok3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok3ActionPerformed
if(drb3.isSelected())
{
    JOptionPane.showMessageDialog(null,fn + ",Your answer is correct");
    score=60000;
    JOptionPane.showMessageDialog(null," Your have won RS "+score);
       
       dlg4.setVisible(false);
       dlg5.setVisible(true);
}
else
{
 JOptionPane.showMessageDialog(null,"Sorry,Your answer is incorrect");
 JOptionPane.showMessageDialog(null,"\t\t GAME OVER");
}// TODO add your handling code here:
}//GEN-LAST:event_ok3ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
System.exit(0);    // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog EXIT;
    private javax.swing.JRadioButton arb;
    private javax.swing.JRadioButton arb1;
    private javax.swing.JRadioButton arb10;
    private javax.swing.JRadioButton arb11;
    private javax.swing.JRadioButton arb2;
    private javax.swing.JRadioButton arb3;
    private javax.swing.JRadioButton arb4;
    private javax.swing.JRadioButton arb5;
    private javax.swing.JRadioButton arb6;
    private javax.swing.JRadioButton arb7;
    private javax.swing.JRadioButton arb8;
    private javax.swing.JRadioButton arb9;
    private javax.swing.JRadioButton brb;
    private javax.swing.JRadioButton brb1;
    private javax.swing.JRadioButton brb10;
    private javax.swing.JRadioButton brb11;
    private javax.swing.JRadioButton brb2;
    private javax.swing.JRadioButton brb3;
    private javax.swing.JRadioButton brb4;
    private javax.swing.JRadioButton brb5;
    private javax.swing.JRadioButton brb6;
    private javax.swing.JRadioButton brb7;
    private javax.swing.JRadioButton brb8;
    private javax.swing.JRadioButton brb9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton crb;
    private javax.swing.JRadioButton crb1;
    private javax.swing.JRadioButton crb10;
    private javax.swing.JRadioButton crb11;
    private javax.swing.JRadioButton crb2;
    private javax.swing.JRadioButton crb3;
    private javax.swing.JRadioButton crb4;
    private javax.swing.JRadioButton crb5;
    private javax.swing.JRadioButton crb6;
    private javax.swing.JRadioButton crb7;
    private javax.swing.JRadioButton crb8;
    private javax.swing.JRadioButton crb9;
    private javax.swing.JDialog dlg;
    private javax.swing.JDialog dlg10;
    private javax.swing.JDialog dlg11;
    private javax.swing.JDialog dlg12;
    private javax.swing.JDialog dlg2;
    private javax.swing.JDialog dlg3;
    private javax.swing.JDialog dlg4;
    private javax.swing.JDialog dlg5;
    private javax.swing.JDialog dlg6;
    private javax.swing.JDialog dlg7;
    private javax.swing.JDialog dlg8;
    private javax.swing.JDialog dlg9;
    private javax.swing.JRadioButton drb;
    private javax.swing.JRadioButton drb1;
    private javax.swing.JRadioButton drb10;
    private javax.swing.JRadioButton drb11;
    private javax.swing.JRadioButton drb2;
    private javax.swing.JRadioButton drb3;
    private javax.swing.JRadioButton drb4;
    private javax.swing.JRadioButton drb5;
    private javax.swing.JRadioButton drb6;
    private javax.swing.JRadioButton drb7;
    private javax.swing.JRadioButton drb8;
    private javax.swing.JRadioButton drb9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lbtg;
    private javax.swing.JTextField ntf;
    private javax.swing.JButton ok;
    private javax.swing.JButton ok1;
    private javax.swing.JButton ok10;
    private javax.swing.JButton ok11;
    private javax.swing.JButton ok2;
    private javax.swing.JButton ok3;
    private javax.swing.JButton ok4;
    private javax.swing.JButton ok5;
    private javax.swing.JButton ok6;
    private javax.swing.JButton ok7;
    private javax.swing.JButton ok8;
    private javax.swing.JButton ok9;
    // End of variables declaration//GEN-END:variables

}
